language: node_js
node_js: stable
branches:
  only:
  - source
cache:
  directories:
  - node_modules
before_install:
- git config --global user.name "hunxiran"
- git config --global user.email "hunxiran@outlook.com"
- npm install -g hexo-cli
- export HEXO_DEPLOYER_REPO=https://${REPO_TOKEN}@github.com/hunxiran/hunxiran.github.io.git master:master
install:
- npm i
script:
- hexo clean
- hexo generate
- hexo deploy
